version: "3.9"

services:
  scraper:
    build: ./scraper_service
    container_name: scraper_service

    ports:
      - "5678:5678"

    volumes:
      - ./scraper_service:/app/scraper_service   
      - scraper_data:/data                      

    stdin_open: true
    tty: true

volumes:
  scraper_data:
